theme = "onedark"

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
# space = "all"
tab = "all"
newline = "none"

# [editor.whitespace.characters]
# space = "·"

[keys.normal]
S-e = "goto_line_end"
Y = "yank_main_selection_to_clipboard"

[keys.select]
Y = "yank_main_selection_to_clipboard"
